services:
  api:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app  # Mount the current directory to /app in the container
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_APP=app_v2.py
      - FLASK_ENV=development
    restart: unless-stopped

